// <auto-generated />
namespace NTNBaiTapLon801.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HoaDon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HoaDon));
        
        string IMigrationMetadata.Id
        {
            get { return "202204121511017_HoaDon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
